> - [8张图让你一步步看清 async/await 和 promise 的执行顺序](https://juejin.cn/post/6844903734321872910)
> - [async/await 原理及执行顺序分析](https://juejin.cn/post/6844903988584775693)


## 1
```js
console.log('script start')

async function async1 () {
    await async2()
    console.log('async1 end')
}
async function async2 () {
    console.log('async2 end')
}
async1()

setTimeout(function () {
    console.log('setTimeout')
}, 0)

new Promise(resolve => {
    console.log('Promise')
    resolve()
})
    .then(function () {
        console.log('promise1')
    })
    .then(function () {
        console.log('promise2')
    })

console.log('script end')
```

> script start => async2 end => Promise => script end => promise1 => promise2 => async1 end => setTimeout


分析这段代码：

- 执行代码，输出script start。
- 执行async1(),会调用async2(),然后输出async2 end,此时将会保留async1函数的上下文，然后跳出async1函数。
- 遇到setTimeout，产生一个宏任务
- 执行Promise，输出Promise。遇到then，产生第一个微任务
- 继续执行代码，输出script end
- 代码逻辑执行完毕(当前宏任务执行完毕)，开始执行当前宏任务产生的微任务队列，输出promise1，该微任务遇到then，产生一个新的微任务
- 执行产生的微任务，输出promise2,当前微任务队列执行完毕。执行权回到async1
- 执行await,实际上会产生一个promise返回，即

let promise_ = new Promise((resolve,reject){ resolve(undefined)})

执行完成，执行await后面的语句，输出async1 end

- 最后，执行下一个宏任务，即执行setTimeout，输出setTimeout

### 注意
新版的chrome浏览器中不是如上打印的，因为chrome优化了,await变得更快了,输出为:
> script start => async2 end => Promise => script end => async1 end => promise1 => promise2 => setTime

我们可以分2种情况来理解：


1. 如果await 后面直接跟的为一个变量，比如：await 1；这种情况的话相当于直接把await后面的代码注册为一个微任务，可以简单理解为promise.then(await下面的代码)。然后跳出async1函数，执行其他代码，当遇到promise函数的时候，会注册promise.then()函数到微任务队列，注意此时微任务队列里面已经存在await后面的微任务。所以这种情况会先执行await后面的代码（async1 end），再执行async1函数后面注册的微任务代码(promise1,promise2)。

1. 如果await后面跟的是一个异步函数的调用，比如上面的代码，将代码改成这样：

```js
console.log('script start')

async function async1() {
    await async2()
    console.log('async1 end')
}
async function async2() {
    console.log('async2 end')
    return Promise.resolve().then(()=>{
    console.log('async2 end1')
    })
}
async1()

setTimeout(function() {
    console.log('setTimeout')
}, 0)

new Promise(resolve => {
    console.log('Promise')
    resolve()
})
.then(function() {
    console.log('promise1')
})
.then(function() {
    console.log('promise2')
})
.then(function() {
    console.log('promise3')
})
.then(function() {
    console.log('promise4')
})

console.log('script end')
```

> script start => async2 end => Promise => script end =>async2 end1 => promise1 => promise2 => async1 end => setTimeout

1. 此时执行完await并不先把await后面的代码注册到微任务队列中去，而是执行完await之后，直接跳出async1函数，执行其他代码。
1. 然后遇到promise的时候，把promise.then注册为微任务。
1. 其他代码执行完毕后，需要回到async1函数去执行剩下的代码，然后把await后面的代码注册到微任务队列当中，注意此时微任务队列中是有之前注册的微任务的。
1. 所以这种情况会先执行async1函数之外的微任务(promise1,promise2)，然后才执行async1内注册的微任务(async1 end).



## 2
```js
new Promise((resolve, reject) => {
  console.log("async1 start");
  console.log("async2");
  resolve(Promise.resolve());
}).then(() => {
  console.log("async1 end");
});

new Promise(function(resolve) {
  console.log("promise1");
  resolve();
}).then(function() {
  console.log("promise2");
}).then(function() {
  console.log("promise3");
}).then(function() {
  console.log("promise4");
});
```


对`resolve`的类型定义中，接受的参数有`PromiseLike`这么个玩意，专业术语叫`thenable`,用人话说就是可以带有`then`方法的对象。

`resolve`在想，老子接受到一个`thenable`，这样输入具有兼容性，但是输出一定要确定（不确定会被打）。所以要把这个`thenable`包装一下，转为正规的Promise。但是这货又比较懒，不想判断这个`thenable`到底是真的Promise，还是`PromiseLike`，就所有的都包装一下，类似下面这样

```js
if(value.then && typeof value.then === 'function') {
    new Promise((res, rej) => {
        value.then(res, rej)
    }).then()
}
```

`resolve(Promise.resolve());`等价于
```js
const thenable = Promise.resolve();
new Promise((res, rej) => {
    thenable.then(res, rej);
}).then(resolve)
```

因此 `resolve(Promise.resolve());`相当于多了两个then

## 3
```js
async function async1 () {
    new Promise(res => {
        console.log('promise start');
        res()
    }).then(() => {
        console.log('promise1')
    }).then(() => {
        console.log('promise11')
    })
    await async2()
    console.log('async1 end')
}
async function async2 () {
    console.log('async2 end');
    new Promise(res => {
        console.log('promise2 start');
        res()
    }).then(() => {
        console.log('promise2')
    }).then(() => {
        console.log('promise22')
    })
}
```
以上async2 没有主动return任何结果，因此会默认return undefined

```js
async function async1 () {
    new Promise(res => {
        console.log('promise start');
        res()
    }).then(() => {
        console.log('promise1')
    }).then(() => {
        console.log('promise11')
    })
    await async2()
    console.log('async1 end')
}
async function async2 () {
    console.log('async2 end');
    return new Promise(res => {
        console.log('promise2 start');
        res()
    }).then(() => {
        console.log('promise2')
    }).then(() => {
        console.log('promise22')
    })
}
```
